apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DPS0340/argoflow
    targetRevision: HEAD
    path: distribution/istio-resources
    kustomize:
      version: v3.2.0
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
