apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oidc-auth
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DPS0340/argoflow
    targetRevision: HEAD
    path: distribution/oidc-auth/base
    kustomize:
      version: v3.2.0
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
